FROM tensorflow/tensorflow:latest

# Set the working directory inside the container
WORKDIR /app

# Copy the application files into the container
COPY . /app

# Install any necessary dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose a port (if needed)
EXPOSE 8501

# Command to run the application
CMD ["python", "app.py"]